# Copyright (C) 2019 VERDOÏA Laurent
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

stages:
  - sanity
  - go-mod
  - check
  - sonar
  - pages

variables:
  PI_DEBUG_TRACE: "true"

shellcheck:
  stage: sanity
  image: koalaman/shellcheck-alpine:v0.7.0
  script:
    - ./build/ci/shared/jobs/shellcheck.sh

shfmt:
  stage: sanity
  image:
    name: mvdan/shfmt:v3.0.2
    entrypoint: [""]
  script:
    - ./build/ci/shared/jobs/shfmt.sh

.go:
  image: golang:1.14.2-buster
  before_script:
    - mkdir -p .cache/go
  cache:
    paths:
      - .cache/go/pkg/mod
    key:
      files:
        - go.mod
        - go.sum
    policy: pull
  variables:
    GOPATH: ${CI_PROJECT_DIR}/.cache/go

go:mod:tidy:
  stage: go-mod
  extends: .go
  script:
    - ./build/ci/shared/jobs/go-mod-tidy.sh
  cache:
    policy: pull-push

go:vet:
  stage: check
  extends: .go
  script:
    - ./build/ci/shared/jobs/go-vet.sh

go:fmt:
  stage: check
  extends: .go
  script:
    - ./build/ci/shared/jobs/go-fmt.sh

go:golangci-lint:
  stage: check
  extends: .go
  image: golangci/golangci-lint:v1.23.8-alpine
  script:
    - ./build/ci/shared/jobs/go-golangci-lint.sh

go:lint:
  stage: check
  image:
    name: registry.gitlab.com/lvjp/docker-golint:alpine
    entrypoint: [""]
  script:
    - ./build/ci/shared/jobs/go-lint.sh
  allow_failure: true

go:test:
  stage: check
  extends: .go
  script:
    - ./build/ci/shared/jobs/go-test.sh
  artifacts:
    paths:
      - dist
    when: always
  coverage: '/total:\t+\(statements\)\t+(\d+\.\d+)%/'

sonar-scanner:
  stage: sonar
  image:
    name: sonarsource/sonar-scanner-cli:4.3
    entrypoint: [""]
  script:
    - ./build/ci/shared/jobs/sonar-scanner.sh
  variables:
    GIT_DEPTH: 0

pages:
  stage: pages
  image: busybox:1.31.1
  script:
    - mkdir public
    - mv dist/coverage.html public/index.html
  artifacts:
    paths:
      - public
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
