# Copyright (C) 2019 VERDOÏA Laurent
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

variables:
  PI_DEBUG_TRACE: "true"

shellcheck:
  image: koalaman/shellcheck-alpine:v0.7.0
  script:
    - ./build/ci/nutshell/jobs/shellcheck.sh

shfmt:
  image:
    name: mvdan/shfmt:v2.6.4
    entrypoint: [""]
  script:
    - ./build/ci/nutshell/jobs/shfmt.sh
